sudo: false
language: python
matrix:
  include:
    - python: 2.7
    - python: 3.5
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true
services:
    - docker
before_install:
    - docker run --name arango -d -p 8529:8529 -e ARANGO_ROOT_PASSWORD=passwd arangodb/arangodb:3.6.1
    - docker cp tests/static/service.zip arango:/tmp/service.zip
install:
    - pip install flake8 mock
    - pip install pytest==3.5.1
    - pip install pytest-cov==2.5.1
    - pip install python-coveralls==2.9.1
    - pip install sphinx sphinx_rtd_theme
    - pip install .
script:
    - python -m flake8
    - python -m sphinx -b doctest docs docs/_build
    - python -m sphinx -b html -W docs docs/_build
    - py.test --complete -s -v --cov=arango
after_success:
    - coveralls